import type {Metadata} from "next";
import "./globals.css";
import Navbar from "@/Components/Navbar/navbar";
import 'remixicon/fonts/remixicon.css'
import Footer from "@/Components/Footer/Footer";

export const metadata: Metadata = {
    title: "Top Notch",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className='min-h-dvh'>
            <Navbar/>
                {children}
            <Footer/>
        </body>
        </html>
    );
}
