import type {Metadata} from "next";
import "./globals.css";
import  Navbar from "@/Components/Navbar/navbar";
import 'remixicon/fonts/remixicon.css'

export const metadata: Metadata = {
    title: "Top Notch",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Navbar/>
                {children}
            </body>
        </html>
    );
}
